import { ProductAttributeDefinition } from "./enrichment";

export interface Product {
  product_code: string;
  product_name: string;
  brand_code: string;
  brand_name: string;
  mfg_code: string;
  mfg_name: string;
  vendor_code: string;
  vendor_name: string;
  industry_name: string;
  category_code: string;
  category_level_1: string;
  category_level_2: string;
  category_level_3: string;
  category_level_4: string;
  category_level_5: string;
  category_level_6: string;
  category_level_7: string;
  category_level_8: string;
  product_type: string;
  sku: string;
  variant_sku: string;
  prod_short_desc: string;
  prod_long_desc: string;
  model_series: string;
  model_no: string;
  mpn: string;
  gtin: string;
  upc: string;
  ean: string;
  unspsc: string;
  feature_1: string;
  feature_2: string;
  feature_3: string;
  feature_4: string;
  feature_5: string;
  feature_6: string;
  feature_7: string;
  feature_8: string;
  meta_title: string;
  meta_desc: string;
  meta_keywords: string;
  related_product_1: string;
  related_product_1_mpn: string;
  related_product_1_name: string;
  related_product_2: string;
  related_product_2_mpn: string;
  related_product_2_name: string;
  related_product_3: string;
  related_product_3_mpn: string;
  related_product_3_name: string;
  related_product_4: string;
  related_product_4_mpn: string;
  related_product_4_name: string;
  related_product_5: string;
  related_product_5_mpn: string;
  related_product_5_name: string;
  pairs_well_with_1: string;
  pairs_well_with_1_mpn: string;
  pairs_well_with_1_name: string;
  pairs_well_with_2: string;
  pairs_well_with_2_mpn: string;
  pairs_well_with_2_name: string;
  pairs_well_with_3: string;
  pairs_well_with_3_mpn: string;
  pairs_well_with_3_name: string;
  pairs_well_with_4: string;
  pairs_well_with_4_mpn: string;
  pairs_well_with_4_name: string;
  pairs_well_with_5: string;
  pairs_well_with_5_mpn: string;
  pairs_well_with_5_name: string;
  image_1_name: string;
  image_1_url: string;
  image_2_name: string;
  image_2_url: string;
  image_3_name: string;
  image_3_url: string;
  image_4_name: string;
  image_4_url: string;
  image_5_name: string;
  image_5_url: string;
  video_1_name: string;
  video_1_url: string;
  video_2_name: string;
  video_2_url: string;
  video_3_name: string;
  video_3_url: string;
  document_1_name: string;
  document_1_url: string;
  document_2_name: string;
  document_2_url: string;
  document_3_name: string;
  document_3_url: string;
  document_4_name: string;
  document_4_url: string;
  document_5_name: string;
  document_5_url: string;
  completeness_score?: number;
  completeness_details?: Record<string, any>;
  created_at?: string;
  updated_at?: string;
  attributes?: Record<string, ProductAttributeDefinition>;
}

export interface ProductFormData extends Partial<Product> {}

export type VariantStatus = 'Base' | 'Variant' | 'Parent';

export interface ProductWithVariantStatus extends Product {
  variant_status: VariantStatus;
  variant_count?: number;
}
